### ISSUE TITLE
How to solve

### ISSUE THREAD

**Issue by kulong51** [eclipse/paho.mqtt.android#187] opened 2017-02-23 08:55 UTC
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

 java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver@2187aed6
                                                                at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:928)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:134)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5377)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                                                             Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference
                                                                at org.eclipse.paho.client.mqttv3.MqttAsyncClient.stopReconnectCycle(MqttAsyncClient.java:1120)
                                                                at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1057)
                                                                at org.eclipse.paho.android.service.MqttConnection.reconnect(MqttConnection.java:1003)
                                                                at org.eclipse.paho.android.service.MqttService.reconnect(MqttService.java:339)
                                                                at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.java:776)
                                                                at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:906)
                                                                at android.os.Handler.handleCallback(Handler.java:739) 
                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                at android.os.Looper.loop(Looper.java:134) 
                                                                at android.app.ActivityThread.main(ActivityThread.java:5377) 
                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.fanfan.zhiwang, PID: 17151
                                                                    java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver@2187aed6
                                                                        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:928)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:134)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5377)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                                                                     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference
                                                                        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.stopReconnectCycle(MqttAsyncClient.java:1120)
                                                                        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1057)
                                                                        at org.eclipse.paho.android.service.MqttConnection.reconnect(MqttConnection.java:1003)
                                                                        at org.eclipse.paho.android.service.MqttService.reconnect(MqttService.java:339)
                                                                        at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.java:776)
                                                                        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:906)
                                                                        at android.os.Handler.handleCallback(Handler.java:739) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:134) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5377) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by jpwsutton** [comment] 2017-02-23 10:44
Hi, this looks like a duplicate of Issue #101, could you confirm using the latest build please?

**Comment by blackadmin** [comment] 2017-03-02 10:30
**I am also facing the same issue using latest stable build 1.1.1, this crash is not on all devices.**

Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 bqHint=4 (has extras) } in org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver@46969ce
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1003)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference
       at org.eclipse.paho.client.mqttv3.MqttAsyncClient.stopReconnectCycle(MqttAsyncClient.java:1120)
       at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1057)
       at org.eclipse.paho.android.service.MqttConnection.reconnect(MqttConnection.java:1049)
       at org.eclipse.paho.android.service.MqttService.reconnect(MqttService.java:342)
       at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.java:827)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:993)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by jpwsutton** [comment] 2017-03-27 08:25
@kulong51 & @blackadmin Hi Can you confirm if using the latest version of this library and the Java client solve this issue please? Can we close this issue?

**Comment by BenjaminZaiser** [comment] 2017-03-31 08:05
I'm facing the same bug using 1.1.1 on Android 7.0 Samsung Galaxy S6.
This issue is **not** related to #101 because it is caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference.
I will try to reproduce this issue now with 1.2-SNAPSHOT and will give you feedback.

**Comment by BenjaminZaiser** [comment] 2017-04-19 16:03
FYI: I found out that the bug is included in org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0 but it has been fixed in 1.1.1 by adding a null check.
I updated now to 1.1.1 and let's see if everything is working fine :-)

**Comment by algrid** [comment] 2017-05-05 17:02
I'm also experiencing this crash. I'm going to try paho.client.mqttv3:1.1.1, thanks @BenjaminZaiser

**Comment by chamroeunbm** [comment] 2017-07-29 04:23
Experience the same crash.  It happened when i disconnect the Internet and reconnect.

I am using paho.client.mqttv3:1.1.1

**Comment by SardarKhan299** [comment] 2017-08-03 05:28
I am also experience the same issue kindly solve it soon thanks here is the stack trace 



Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver@d08950d
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:974)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:179)
       at android.app.ActivityThread.main(ActivityThread.java:5730)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference
       at org.eclipse.paho.client.mqttv3.MqttAsyncClient.stopReconnectCycle(MqttAsyncClient.java:1120)
       at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1057)
       at org.eclipse.paho.android.service.MqttConnection.reconnect(MqttConnection.java:1049)
       at org.eclipse.paho.android.service.MqttService.reconnect(MqttService.java:342)
       at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.java:827)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:957)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:179)
       at android.app.ActivityThread.main(ActivityThread.java:5730)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)

**Comment by androAxii** [comment] 2017-08-05 10:46
This ISSUE solved in my case : remove "mqttConnectOptions.setAutomaticReconnect(true)" this line. And I am using Gradle : compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0'
                             compile 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

**Comment by omarhayatsatti** [comment] 2017-08-22 10:43
If we remove "mqttConnectOptions.setAutomaticReconnect(true)" this line how it reconnect to internet automatically?

**Comment by androAxii** [comment] 2017-08-22 11:55
If i m loosing connection of mqtt then i'm trying to connect mqtt with the same client id. so i m not using setAutomaticReconnect. I know it's not proper way but it's work for me!! Also use "mqttConnectOptions.setKeepAliveInterval(60)" for 60 secs interval between messages sent or received.

**Comment by varunam** [comment] 2019-03-12 05:42
Any updates on this thread? I am still facing this issue.
Below are the dependencies used
implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.1'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

**Comment by brunohorta82** [comment] 2019-04-06 14:29
I have the same issue 
  implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.1'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

**Comment by jackson140389** [comment] 2019-05-14 11:07
I have the same issue
implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.1'
implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

**Comment by xmanjimmy** [comment] 2019-05-21 10:52
same issue here, 
implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.1'
implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

**Closed** 2019-05-22 03:05 UTC
Labels: triage

**Comment by acaliaro** [comment] 2020-01-14 09:04
Why this issue has been closed?
