### ISSUE TITLE
LOST connect Every 2-3min

### ISSUE THREAD

**Issue by gallex** [eclipse/paho.mqtt.android#124] opened 2016-09-25 09:58 UTC
Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.0.2 

__Android API Version Bug Seen on:__ 19

__Android Version Bug Seen on:__ 5.0

Yes, it is under Android , but I just only use NORMAL JAVA lib, so I put here.

the stranger is : when connected DEVICE to ADT, every thing is OK, otherwise it would lost connection about every 3-4min.

after debug : I found the error is cause by readMqttWireMessage(), when perform in.readByte() is get a EOFEception. 
E.g. Steps to re-create, how often does this happen etc..

**Comment by gallex** [comment] 2016-09-26 04:26
I found reason:

the default KeepAlive option is 60s, this is effect on both Server and Client. that means server (or client ) would close the connect no packet received after 2*KeepAlive time (is correct ?), normally it' fine because client would send a Ping packet every KeepAlive time . But android client would sleep, ping ping packet would send delay, so the race between Server and Android Client , server always win: it close the connection.

Set KeepAlive time big than android wake up delay may resolve the problem. As for my test, 300s is OK.

**Comment by jpwsutton** [comment] 2016-09-27 08:56
Duplicate of https://github.com/eclipse/paho.mqtt.java/issues/270

**Closed by jpwsutton** 2016-09-27 08:56 UTC
Labels: duplicate
