### ISSUE TITLE
Client <client name> has exceeded timeout, disconnecting.

### ISSUE THREAD

**Issue by northxx10** [eclipse/paho.mqtt.android#95] opened 2016-07-04 03:04 UTC
Please fill out the form below before submitting, thank you!

- [ x] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [ x] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on: 23

__Android Version Bug Seen on: 5.1.1

Please also check that if you have found the bug in the Release version (1.1.0) that you check that it also exists in the Snapshot (1.1.1-SNAPSHOT) before raising a bug.

## Description of Bug:

I am developing an Android mobile app that starts a service that persists after the application is closed.
The server side is Mosquitto version 1.4.8 as an MQTT v3.1 broker.
The service runs properly sends pings at the right time as long as the mobile device is not in a sleep mode.

When the phone is put in a sleep mode, the client does not send pings anymore, I get the following error:
**Client <client name> has exceeded timeout, disconnecting.**

From looking at Wireshark traces, it is the server that initiates the closer of the socket, after 1.5x of the keepalive interval, because the client is not sending pings anymore.

I would appreciate any help with this.

Thanks in advance.

**Comment by jpwsutton** [comment] 2016-10-13 15:25
This is likely a duplicate of Issue #104, As of Android M and N, the standby mode is a lot more aggressive and prevents network connectivity when dozing. Currently the best workaround we have so far is to use Google Cloud Messaging (GCM) high priority messages to wake your app up so that it can receive messages, this depends on the application though.

**Closed by jpwsutton** 2016-10-13 15:25 UTC
Labels: bug
